//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ISample
{
	id: number;
	/** UTC date of creation */
	create_timestamp: Date;
	code: string;
}
